from enum import StrEnum


class LicenseType(StrEnum):
    TRIAL = "TRIAL"
    MONTHLY = "monthly"
    YEARLY = "yearly"
    PERMANENT = "permanent"
    FIXED_DATE = "fixed_date"


class LicenseStatus(StrEnum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    DISABLED = "DISABLED"
    REVOKED = "REVOKED"


class BindingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEACTIVATED = "DEACTIVATED"
    DISABLED = "DISABLED"


class SigningKeyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RETIRING = "RETIRING"
    RETIRED = "RETIRED"


class LicenseEventType(StrEnum):
    TRIAL_ACTIVATED = "TRIAL_ACTIVATED"
    TRIAL_REACTIVATED_SAME_DEVICE = "TRIAL_REACTIVATED_SAME_DEVICE"
    TRIAL_VERIFIED = "TRIAL_VERIFIED"
    TRIAL_EXPIRED = "TRIAL_EXPIRED"
    TRIAL_CONVERTED = "TRIAL_CONVERTED"
    TRIAL_DISABLED = "TRIAL_DISABLED"
    TRIAL_ACTIVATION_FAILED = "TRIAL_ACTIVATION_FAILED"
    TRIAL_RECORDING_BLOCKED = "TRIAL_RECORDING_BLOCKED"
    TRIAL_RESET = "TRIAL_RESET"
    TRIAL_EXTENDED = "TRIAL_EXTENDED"
    TRIAL_DELETED = "TRIAL_DELETED"
    TRIAL_REACTIVATED_AFTER_DELETE = "TRIAL_REACTIVATED_AFTER_DELETE"
    ACTIVATED = "ACTIVATED"
    REACTIVATED_SAME_DEVICE = "REACTIVATED_SAME_DEVICE"
    VERIFIED = "VERIFIED"
    REFRESHED = "REFRESHED"
    DEACTIVATED = "DEACTIVATED"
    ACTIVATION_FAILED = "ACTIVATION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    DEACTIVATION_FAILED = "DEACTIVATION_FAILED"
    REFRESH_FAILED = "REFRESH_FAILED"
    LICENSE_DISABLED = "LICENSE_DISABLED"
    LICENSE_ENABLED = "LICENSE_ENABLED"
    LICENSE_REVOKED = "LICENSE_REVOKED"
    ADMIN_DEACTIVATED = "ADMIN_DEACTIVATED"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"
    ABNORMAL_REQUEST = "ABNORMAL_REQUEST"


class AdminRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    AUDITOR = "AUDITOR"


class AdminStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class AdminSessionStatus(StrEnum):
    PENDING_TOTP = "PENDING_TOTP"
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class DeviceTrialStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CONVERTED = "CONVERTED"
    DISABLED = "DISABLED"
    DELETED = "DELETED"
