from enum import StrEnum


class LicenseType(StrEnum):
    MONTHLY = "monthly"
    YEARLY = "yearly"
    PERMANENT = "permanent"
    FIXED_DATE = "fixed_date"


class LicenseStatus(StrEnum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    DISABLED = "DISABLED"
    REVOKED = "REVOKED"


class BindingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEACTIVATED = "DEACTIVATED"
    DISABLED = "DISABLED"


class SigningKeyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class LicenseEventType(StrEnum):
    ACTIVATED = "ACTIVATED"
    REACTIVATED_SAME_DEVICE = "REACTIVATED_SAME_DEVICE"
    VERIFIED = "VERIFIED"
    REFRESHED = "REFRESHED"
    DEACTIVATED = "DEACTIVATED"
    ACTIVATION_FAILED = "ACTIVATION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    DEACTIVATION_FAILED = "DEACTIVATION_FAILED"
    REFRESH_FAILED = "REFRESH_FAILED"
    LICENSE_DISABLED = "LICENSE_DISABLED"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"
    ABNORMAL_REQUEST = "ABNORMAL_REQUEST"

