server {
    listen 80;
    listen [::]:80;
    server_name download.aixcc.top;

    access_log /var/log/nginx/ddrec-downloads-access.log;
    error_log /var/log/nginx/ddrec-downloads-error.log warn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
