from __future__ import annotations


PRODUCT_DISPLAY_NAME = "iVRec"
PRODUCT_PACKAGE_NAME = "iVRec"

# Current protocol identity. Historical values remain explicit for immutable
# signed payloads, release rows, audits, and migration recognition.
LEGACY_LICENSE_PROTOCOL_PRODUCT = "DDREC"
TARGET_LICENSE_PROTOCOL_PRODUCT = "iVRec"
ACTIVE_LICENSE_PROTOCOL_PRODUCT = TARGET_LICENSE_PROTOCOL_PRODUCT

LEGACY_UPDATE_PROTOCOL_PRODUCT = "DDREC"
TARGET_UPDATE_PROTOCOL_PRODUCT = "iVRec"
ACTIVE_UPDATE_PROTOCOL_PRODUCT = TARGET_UPDATE_PROTOCOL_PRODUCT

ADMIN_TOTP_ISSUER_NAME = "iVRec License Admin"
