<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { licensesApi } from '@/api/licenses'
import PageHeader from '@/components/PageHeader.vue'
import StatusTag from '@/components/StatusTag.vue'
import { formatUtc } from '@/utils/date'
import { apiErrorMessage } from '@/utils/errors'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const canWrite=computed(()=>auth.user?.role==='OWNER'||auth.user?.role==='ADMIN')
const route=useRoute();const loading=ref(false);const detail=ref<any>(null);const edit=reactive({customerName:'',customerContact:'',remark:''})
async function load(){loading.value=true;try{detail.value=(await licensesApi.detail(String(route.params.id))).data.license;Object.assign(edit,{customerName:detail.value.customerName||'',customerContact:detail.value.customerContact||'',remark:detail.value.remark||''})}finally{loading.value=false}}
async function save(){try{await licensesApi.update(detail.value.licenseId,edit);ElMessage.success('客户信息已保存');await load()}catch(e){ElMessage.error(apiErrorMessage(e))}}
async function reasonAction(action:'disable'|'enable'|'revoke'){const irreversible=action==='revoke';try{const {value}=await ElMessageBox.prompt(irreversible?'撤销后不可恢复，请输入撤销原因':'请输入操作原因',irreversible?'永久撤销授权':'确认操作',{confirmButtonText:irreversible?'确认永久撤销':'确认',cancelButtonText:'取消',inputValidator:v=>v.length>=3||'原因至少3个字',type:irreversible?'error':'warning'});await licensesApi[action](detail.value.licenseId,value);ElMessage.success('授权状态已更新');await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(apiErrorMessage(e))}}
async function unbind(id:string){try{const {value}=await ElMessageBox.prompt('解绑后旧设备凭据立即失效，但不会删除客户业务数据。请输入原因。','解绑设备',{type:'warning',inputValidator:v=>v.length>=3||'原因至少3个字'});await licensesApi.deactivateBinding(id,value);ElMessage.success('设备已解绑');await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(apiErrorMessage(e))}}
onMounted(load)
</script>
<template><div class="page" v-loading="loading"><PageHeader title="授权详情" description="授权历史规则和审计记录不可修改"><div v-if="detail&&canWrite" class="buttons"><el-button v-if="detail.status==='DISABLED'" @click="reasonAction('enable')">恢复授权</el-button><el-button v-else-if="!['REVOKED','EXPIRED'].includes(detail.status)" type="warning" plain @click="reasonAction('disable')">禁用授权</el-button><el-button v-if="detail.status!=='REVOKED'" type="danger" plain @click="reasonAction('revoke')">永久撤销</el-button></div></PageHeader><template v-if="detail"><section class="surface block"><div class="section-title"><h2>基本信息</h2><StatusTag :status="detail.status"/></div><el-descriptions :column="3" border><el-descriptions-item label="License ID"><span class="mono">{{ detail.licenseId }}</span></el-descriptions-item><el-descriptions-item label="激活码"><span class="mono">{{ detail.maskedCode }}</span></el-descriptions-item><el-descriptions-item label="类型">{{ detail.licenseType }}</el-descriptions-item><el-descriptions-item label="首次激活">{{ formatUtc(detail.activatedAt) }}</el-descriptions-item><el-descriptions-item label="到期时间">{{ formatUtc(detail.expiresAt) }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ formatUtc(detail.createdAt) }}</el-descriptions-item></el-descriptions></section><section class="surface block"><h2>客户信息</h2><el-form label-position="top"><div class="edit-grid"><el-form-item label="客户名称"><el-input v-model="edit.customerName" :disabled="!canWrite"/></el-form-item><el-form-item label="联系方式"><el-input v-model="edit.customerContact" :disabled="!canWrite"/></el-form-item></div><el-form-item label="备注"><el-input v-model="edit.remark" type="textarea" :rows="3" :disabled="!canWrite"/></el-form-item><el-button v-if="canWrite" type="primary" @click="save">保存客户信息</el-button><span class="renewal">续期功能尚未开放</span></el-form></section><section class="surface block"><h2>设备绑定</h2><el-table :data="detail.bindings"><el-table-column prop="device" label="设备编号"/><el-table-column prop="deviceName" label="设备名称"/><el-table-column prop="appVersion" label="客户端版本"/><el-table-column label="状态"><template #default="s"><StatusTag :status="s.row.status"/></template></el-table-column><el-table-column label="最后验证"><template #default="s">{{ formatUtc(s.row.lastVerifiedAt) }}</template></el-table-column><el-table-column v-if="canWrite" label="操作" width="100"><template #default="s"><el-button v-if="s.row.status==='ACTIVE'" link type="danger" @click="unbind(s.row.bindingId)">解绑</el-button></template></el-table-column></el-table></section><section class="surface block"><h2>最近授权事件</h2><el-table :data="detail.events"><el-table-column prop="eventType" label="事件"/><el-table-column prop="result" label="结果"/><el-table-column prop="requestId" label="请求 ID" show-overflow-tooltip/><el-table-column label="时间"><template #default="s">{{ formatUtc(s.row.createdAt) }}</template></el-table-column></el-table></section></template></div></template>
<style scoped>.buttons{display:flex;gap:8px}.block{padding:18px;margin-bottom:14px}.block h2,.section-title h2{font-size:16px;margin:0 0 14px}.section-title{display:flex;justify-content:space-between;align-items:start}.edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.renewal{margin-left:14px;color:var(--text-muted);font-size:13px}</style>
